"""
train_rhyme_model.py

Training script for the Prosodic RhymeSiameseNet.

Loads labeled phoneme pair data from training_data.json (generated by
data_generator.py), trains the Siamese BiGRU network for 50 epochs,
and saves the best model to models/rhyme_model.pt.

Usage:
    python train_rhyme_model.py

Prerequisites:
    1. pip install torch nltk  (see Step 14 for full pip install list)
    2. python data_generator.py  (generates training_data.json, ~5-10 min)
    3. python train_rhyme_model.py  (this script, ~20-40 min on i9 CPU)

Estimated training time: 20–40 min on i9 CPU (no GPU required).
GPU will be used automatically if available (CUDA or MPS).

Output:
    models/rhyme_model.pt  — best checkpoint by validation loss
    prosodic_errors.log    — any errors encountered during training
"""

# NOTE: This file is NOT executed by Claude Code (Rule 8).
# It is verified for syntax correctness and import resolution only.
# Run it manually after data_generator.py completes.

import json
import logging
import os
import random
import sys
from typing import Dict, List, Optional, Tuple

import torch
import torch.nn as nn
from torch.utils.data import DataLoader, Dataset

from ml.models.rhyme_siamese.model import (
    VOCAB,
    ContrastiveLoss,
    PhonemeVocab,
    RhymeSiameseNet,
    load_model,
    save_model,
)

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

TRAINING_DATA_PATH = os.path.join(os.path.dirname(__file__), "training_data.json")
MODEL_OUTPUT_PATH  = os.path.join(os.path.dirname(__file__), "models", "rhyme_model.pt")
ERROR_LOG_PATH     = os.path.join(os.path.dirname(__file__), "prosodic_errors.log")

BATCH_SIZE    = 64
LEARNING_RATE = 0.001
NUM_EPOCHS    = 50
TRAIN_SPLIT   = 0.80
RANDOM_SEED   = 42
CONTRASTIVE_MARGIN = 0.3

# Similarity score → binary label threshold for contrastive loss.
# Pairs with score >= POSITIVE_THRESHOLD are treated as positive (rhyme).
POSITIVE_THRESHOLD = 0.50

# ---------------------------------------------------------------------------
# Logger
# ---------------------------------------------------------------------------

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [train] %(message)s",
    handlers=[
        logging.StreamHandler(sys.stdout),
        logging.FileHandler(ERROR_LOG_PATH, encoding="utf-8"),
    ],
)
logger = logging.getLogger("prosodic_train")


# ---------------------------------------------------------------------------
# Dataset
# ---------------------------------------------------------------------------

class RhymePairDataset(Dataset):
    """
    PyTorch Dataset wrapping labeled phoneme pairs from training_data.json.

    Each item returns encoded tensor pairs and a soft contrastive label.
    The similarity_score from the generator is used directly as the label
    so the loss can learn from partial rhyme strength, not just 0/1.

    Attributes:
        pairs:  List of pair dicts from training_data.json.
        vocab:  PhonemeVocab for encoding phoneme lists to indices.
    """

    def __init__(self, pairs: List[dict], vocab: PhonemeVocab) -> None:
        """
        Initialize dataset.

        Args:
            pairs: List of pair dicts with keys word_a, word_b,
                   phonemes_a, phonemes_b, label, similarity_score.
            vocab: PhonemeVocab instance for encoding.
        """
        self.pairs = pairs
        self.vocab = vocab

    def __len__(self) -> int:
        """Return total number of pairs."""
        return len(self.pairs)

    def __getitem__(self, idx: int) -> Tuple[torch.Tensor, torch.Tensor, torch.Tensor, torch.Tensor, torch.Tensor]:
        """
        Return encoded tensors for one pair.

        Returns:
            phonemes_a:  LongTensor (max_length,)
            stress_a:    LongTensor (max_length,)
            phonemes_b:  LongTensor (max_length,)
            stress_b:    LongTensor (max_length,)
            label:       FloatTensor scalar — similarity_score [0.0, 1.0]
        """
        pair = self.pairs[idx]
        ph_a = pair.get("phonemes_a", [])
        ph_b = pair.get("phonemes_b", [])
        label = float(pair.get("similarity_score", 0.0))

        idx_a = self.vocab.encode(ph_a)
        str_a = self.vocab.encode_stress(ph_a)
        idx_b = self.vocab.encode(ph_b)
        str_b = self.vocab.encode_stress(ph_b)

        return idx_a, str_a, idx_b, str_b, torch.tensor(label, dtype=torch.float32)


# ---------------------------------------------------------------------------
# Data loading
# ---------------------------------------------------------------------------

def load_training_data(path: str) -> List[dict]:
    """
    Load and validate training pairs from training_data.json.

    Args:
        path: Path to training_data.json produced by data_generator.py.

    Returns:
        List of pair dicts. Exits with error message if file not found.
    """
    if not os.path.isfile(path):
        print(f"\nERROR: {path} not found.")
        print("Run: python data_generator.py  (takes 5–10 min)")
        sys.exit(1)

    with open(path, "r", encoding="utf-8") as f:
        data = json.load(f)

    pairs = data.get("pairs", [])
    if not pairs:
        print(f"ERROR: No pairs found in {path}")
        sys.exit(1)

    # Filter out pairs with missing phoneme data
    valid = [
        p for p in pairs
        if p.get("phonemes_a") and p.get("phonemes_b")
    ]
    skipped = len(pairs) - len(valid)
    if skipped:
        logger.warning("Skipped %d pairs with missing phoneme data", skipped)

    return valid


def split_data(
    pairs: List[dict],
    train_ratio: float = TRAIN_SPLIT,
    seed: int = RANDOM_SEED,
) -> Tuple[List[dict], List[dict]]:
    """
    Shuffle and split pairs into train/val sets, stratified by label.

    Stratification ensures each split has the same label distribution,
    preventing a train set dominated by one rhyme type.

    Args:
        pairs:       Full list of pair dicts.
        train_ratio: Fraction of data for training (default 0.80).
        seed:        Random seed for reproducibility.

    Returns:
        Tuple of (train_pairs, val_pairs).
    """
    rng = random.Random(seed)

    # Group by label
    by_label: Dict[str, List[dict]] = {}
    for p in pairs:
        lbl = p.get("label", "none")
        by_label.setdefault(lbl, []).append(p)

    train, val = [], []
    for lbl, group in by_label.items():
        rng.shuffle(group)
        split_idx = int(len(group) * train_ratio)
        train.extend(group[:split_idx])
        val.extend(group[split_idx:])

    rng.shuffle(train)
    rng.shuffle(val)

    return train, val


# ---------------------------------------------------------------------------
# Training utilities
# ---------------------------------------------------------------------------

def _get_device() -> torch.device:
    """
    Select the best available compute device.

    Prefers CUDA, then MPS (Apple Silicon), then CPU.
    Prints selection so the user knows which device is active.
    """
    if torch.cuda.is_available():
        device = torch.device("cuda")
        print(f"  Device: CUDA ({torch.cuda.get_device_name(0)})")
    elif hasattr(torch.backends, "mps") and torch.backends.mps.is_available():
        device = torch.device("mps")
        print("  Device: Apple MPS")
    else:
        device = torch.device("cpu")
        print("  Device: CPU")
    return device


def _print_label_distribution(name: str, pairs: List[dict]) -> None:
    """Print the label distribution of a dataset split to stdout."""
    counts: Dict[str, int] = {}
    for p in pairs:
        lbl = p.get("label", "none")
        counts[lbl] = counts.get(lbl, 0) + 1
    print(f"  {name}: {len(pairs):,} pairs")
    for lbl in ["perfect", "slant", "near", "none"]:
        print(f"    {lbl:<10} {counts.get(lbl, 0):>6,}")


def _run_epoch(
    model: RhymeSiameseNet,
    loader: DataLoader,
    loss_fn: ContrastiveLoss,
    optimizer: Optional[torch.optim.Optimizer],
    device: torch.device,
    training: bool,
) -> Tuple[float, List[Tuple[str, str, float, float]]]:
    """
    Run one full pass over a DataLoader (train or eval).

    Args:
        model:     RhymeSiameseNet instance.
        loader:    DataLoader for train or val set.
        loss_fn:   ContrastiveLoss.
        optimizer: Adam optimizer (None during eval).
        device:    Compute device.
        training:  True for train mode, False for eval mode.

    Returns:
        Tuple of (mean_loss, sample_pairs) where sample_pairs is a list
        of up to 5 (word_a, word_b, predicted_score, true_label) tuples
        collected from the last batch, for progress printing.
    """
    model.train(training)
    context = torch.enable_grad() if training else torch.no_grad()
    total_loss = 0.0
    n_batches = 0
    sample_pairs: List[Tuple[str, str, float, float]] = []

    with context:
        for batch in loader:
            idx_a, str_a, idx_b, str_b, labels = [t.to(device) for t in batch]

            scores = model(idx_a, str_a, idx_b, str_b)
            loss = loss_fn(scores, labels)

            if training and optimizer is not None:
                optimizer.zero_grad()
                loss.backward()
                # Gradient clipping — prevents exploding gradients on short sequences
                nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
                optimizer.step()

            total_loss += loss.item()
            n_batches += 1

    mean_loss = total_loss / max(n_batches, 1)
    return mean_loss, sample_pairs


def _collect_sample_pairs(
    model: RhymeSiameseNet,
    val_pairs: List[dict],
    vocab: PhonemeVocab,
    device: torch.device,
    n: int = 5,
    seed: int = 0,
) -> None:
    """
    Print n random sample predictions from the val set.

    Shows: word_a | word_b | true_label | predicted_score
    Called every 10 epochs to show learning progress.

    Args:
        model:     Model in eval mode.
        val_pairs: Validation pair list.
        vocab:     PhonemeVocab.
        device:    Compute device.
        n:         Number of samples to print.
        seed:      Random seed for sample selection.
    """
    rng = random.Random(seed)
    samples = rng.sample(val_pairs, min(n, len(val_pairs)))

    model.eval()
    with torch.no_grad():
        for p in samples:
            ph_a = p.get("phonemes_a", [])
            ph_b = p.get("phonemes_b", [])
            true_score = p.get("similarity_score", 0.0)
            label = p.get("label", "?")

            score = model.score(ph_a, ph_b, vocab=vocab, device=device)
            wa = p.get("word_a", "?")
            wb = p.get("word_b", "?")
            print(f"    {wa:<14} {wb:<14} label={label:<8} true={true_score:.2f}  pred={score:.4f}")


# ---------------------------------------------------------------------------
# Post-training validation
# ---------------------------------------------------------------------------

# 10 hard-coded test pairs with expected outcomes.
# These are the ground-truth benchmark used to confirm the model learned correctly.
# PASS = predicted score falls within the expected range.
VALIDATION_PAIRS = [
    # ER family (AAVE-relevant) — should score HIGH (rhyme)
    {"word_a": "hurt",    "phonemes_a": ["HH","ER1","T"],
     "word_b": "work",    "phonemes_b": ["W","ER1","K"],
     "expected": "rhyme",  "min_score": 0.60, "max_score": 1.0,
     "note": "ER family — same vowel nucleus"},

    {"word_a": "hurt",    "phonemes_a": ["HH","ER1","T"],
     "word_b": "birth",   "phonemes_b": ["B","ER1","TH"],
     "expected": "rhyme",  "min_score": 0.60, "max_score": 1.0,
     "note": "ER family — perfect-ish"},

    # Slant rhymes — should score MEDIUM-HIGH
    {"word_a": "mind",    "phonemes_a": ["M","AY1","N","D"],
     "word_b": "time",    "phonemes_b": ["T","AY1","M"],
     "expected": "slant",  "min_score": 0.45, "max_score": 1.0,
     "note": "AY slant — same vowel, different coda"},

    {"word_a": "gone",    "phonemes_a": ["G","AO1","N"],
     "word_b": "strong",  "phonemes_b": ["S","T","R","AO1","NG"],
     "expected": "slant",  "min_score": 0.40, "max_score": 1.0,
     "note": "AO slant — same vowel, different context"},

    # Near rhymes — should score MEDIUM
    {"word_a": "love",    "phonemes_a": ["L","AH1","V"],
     "word_b": "move",    "phonemes_b": ["M","UW1","V"],
     "expected": "near",   "min_score": 0.20, "max_score": 0.75,
     "note": "near — shared coda /V/, different vowel"},

    {"word_a": "day",     "phonemes_a": ["D","EY1"],
     "word_b": "free",    "phonemes_b": ["F","R","IY1"],
     "expected": "near",   "min_score": 0.10, "max_score": 0.65,
     "note": "near/none boundary — different vowel, no coda"},

    # No-rhyme pairs — should score LOW
    {"word_a": "cat",     "phonemes_a": ["K","AE1","T"],
     "word_b": "justice", "phonemes_b": ["JH","AH1","S","T","IH0","S"],
     "expected": "none",   "min_score": 0.0,  "max_score": 0.35,
     "note": "no rhyme"},

    {"word_a": "fire",    "phonemes_a": ["F","AY1","R"],
     "word_b": "table",   "phonemes_b": ["T","EY1","B","AH0","L"],
     "expected": "none",   "min_score": 0.0,  "max_score": 0.35,
     "note": "no rhyme"},

    # Spelling-similar adversarial — should score LOW despite visual similarity
    {"word_a": "cough",   "phonemes_a": ["K","AO1","F"],
     "word_b": "rough",   "phonemes_b": ["R","AH1","F"],
     "expected": "none",   "min_score": 0.0,  "max_score": 0.45,
     "note": "spelling similar but different vowel — AO vs AH"},

    {"word_a": "love",    "phonemes_a": ["L","AH1","V"],
     "word_b": "prove",   "phonemes_b": ["P","R","UW1","V"],
     "expected": "none",   "min_score": 0.0,  "max_score": 0.45,
     "note": "spelling similar but different vowel — AH vs UW"},
]


def run_post_training_validation(
    model: RhymeSiameseNet,
    vocab: PhonemeVocab,
    device: torch.device,
) -> None:
    """
    Run 10 hard-coded validation pairs and print PASS/FAIL for each.

    A pair PASSES if the predicted score falls within [min_score, max_score].
    A pair FAILS if the score is outside that range.

    Prints a summary with pass count and overall PASS/FAIL verdict.

    Args:
        model:  Trained RhymeSiameseNet.
        vocab:  PhonemeVocab.
        device: Compute device.
    """
    print("\n" + "=" * 68)
    print("POST-TRAINING VALIDATION")
    print("=" * 68)
    print(f"{'Word A':<12} {'Word B':<12} {'Expected':<8} {'Score':>7}  {'Range':<16} {'Result'}")
    print("-" * 68)

    passed = 0
    total = len(VALIDATION_PAIRS)

    model.eval()
    with torch.no_grad():
        for vp in VALIDATION_PAIRS:
            score = model.score(
                vp["phonemes_a"],
                vp["phonemes_b"],
                vocab=vocab,
                device=device,
            )
            lo = vp["min_score"]
            hi = vp["max_score"]
            result = "PASS" if lo <= score <= hi else "FAIL"
            if result == "PASS":
                passed += 1

            range_str = f"[{lo:.2f} – {hi:.2f}]"
            print(
                f"{vp['word_a']:<12} {vp['word_b']:<12} "
                f"{vp['expected']:<8} {score:>7.4f}  "
                f"{range_str:<16} {result}  ({vp['note']})"
            )

    print("-" * 68)
    print(f"Result: {passed}/{total} PASS")
    if passed == total:
        print("Overall: PASS — model is ready for use")
    elif passed >= total * 0.8:
        print(f"Overall: PARTIAL PASS — {total - passed} pair(s) outside expected range")
        print("Consider retraining with more epochs or checking training data quality.")
    else:
        print(f"Overall: FAIL — {total - passed} pair(s) failed")
        print("Training may not have converged. Check loss curve and training data.")
    print("=" * 68)


# ---------------------------------------------------------------------------
# Main training loop
# ---------------------------------------------------------------------------

def train() -> None:
    """
    Full training pipeline for RhymeSiameseNet.

    Steps:
        1. Load training_data.json
        2. 80/20 stratified train/val split
        3. Build DataLoaders
        4. Initialize model, Adam optimizer, ContrastiveLoss
        5. Train for 50 epochs, print loss every epoch
        6. Print 5 sample predictions every 10 epochs
        7. Save best model to models/rhyme_model.pt (lowest val loss)
        8. Post-training validation on 10 benchmark pairs
    """
    print("=" * 68)
    print("PROSODIC — RhymeSiameseNet Training")
    print("Estimated time: 20–40 min on i9 CPU")
    print("=" * 68)

    # --- Device ---
    device = _get_device()

    # --- Data ---
    print("\n[1/4] Loading training data...")
    pairs = load_training_data(TRAINING_DATA_PATH)
    print(f"  Loaded {len(pairs):,} valid pairs from {TRAINING_DATA_PATH}")

    train_pairs, val_pairs = split_data(pairs)
    print(f"\n  Split: {len(train_pairs):,} train / {len(val_pairs):,} val (80/20 stratified)")
    _print_label_distribution("Train", train_pairs)
    _print_label_distribution("Val  ", val_pairs)

    train_ds = RhymePairDataset(train_pairs, VOCAB)
    val_ds   = RhymePairDataset(val_pairs, VOCAB)

    train_loader = DataLoader(
        train_ds,
        batch_size=BATCH_SIZE,
        shuffle=True,
        num_workers=0,   # 0 for Windows compatibility
        pin_memory=(device.type == "cuda"),
    )
    val_loader = DataLoader(
        val_ds,
        batch_size=BATCH_SIZE,
        shuffle=False,
        num_workers=0,
    )

    # --- Model, optimizer, loss ---
    print("\n[2/4] Initializing model...")
    model = RhymeSiameseNet().to(device)
    total_params = sum(p.numel() for p in model.parameters())
    print(f"  RhymeSiameseNet: {total_params:,} parameters")

    optimizer = torch.optim.Adam(model.parameters(), lr=LEARNING_RATE)

    # Learning rate scheduler: halve LR if val loss plateaus for 5 epochs
    scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
        optimizer, mode="min", factor=0.5, patience=5, verbose=True
    )

    loss_fn = ContrastiveLoss(margin=CONTRASTIVE_MARGIN)

    # --- Training loop ---
    print(f"\n[3/4] Training for {NUM_EPOCHS} epochs...")
    print(f"  Batch size: {BATCH_SIZE}, LR: {LEARNING_RATE}, Margin: {CONTRASTIVE_MARGIN}")
    print("-" * 68)
    print(f"{'Epoch':>5}  {'Train Loss':>12}  {'Val Loss':>10}  {'Best':>6}  {'LR':>10}")
    print("-" * 68)

    best_val_loss = float("inf")
    best_epoch = 0

    for epoch in range(1, NUM_EPOCHS + 1):
        # Train
        train_loss, _ = _run_epoch(
            model, train_loader, loss_fn, optimizer, device, training=True
        )

        # Validate
        val_loss, _ = _run_epoch(
            model, val_loader, loss_fn, None, device, training=False
        )

        # LR schedule step
        scheduler.step(val_loss)
        current_lr = optimizer.param_groups[0]["lr"]

        # Track best model
        is_best = val_loss < best_val_loss
        if is_best:
            best_val_loss = val_loss
            best_epoch = epoch
            os.makedirs(os.path.dirname(MODEL_OUTPUT_PATH), exist_ok=True)
            save_model(
                model,
                MODEL_OUTPUT_PATH,
                metadata={
                    "epoch": epoch,
                    "train_loss": train_loss,
                    "val_loss": val_loss,
                    "best": True,
                },
            )

        best_marker = "*" if is_best else " "
        print(
            f"{epoch:>5}  {train_loss:>12.6f}  {val_loss:>10.6f}  "
            f"{best_marker:>6}  {current_lr:>10.6f}"
        )

        # Sample predictions every 10 epochs
        if epoch % 10 == 0:
            print(f"\n  --- Sample predictions at epoch {epoch} ---")
            _collect_sample_pairs(model, val_pairs, VOCAB, device, n=5, seed=epoch)
            print()

    print("-" * 68)
    print(f"\n  Best model: epoch {best_epoch}, val_loss={best_val_loss:.6f}")
    print(f"  Saved to: {MODEL_OUTPUT_PATH}")

    # --- Load best model for validation ---
    print("\n[4/4] Loading best checkpoint for post-training validation...")
    best_model = load_model(MODEL_OUTPUT_PATH, device=device)

    # --- Post-training validation ---
    run_post_training_validation(best_model, VOCAB, device)


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    torch.manual_seed(RANDOM_SEED)
    random.seed(RANDOM_SEED)
    train()
