const DEVICES = [
  { name: 'Abating', category: 'Classical Rhetoric', definition: "Reducing the force of an argument or charge through qualification or counterpoint." },
  { name: 'Abcisio', category: 'Brevity & Omission', definition: "Breaking off speech mid-thought — leaving a sentence incomplete for dramatic effect. A classical form of aposiopesis." },
  { name: 'Ablatio', category: 'Classical Rhetoric', definition: "Removal of an element from an argument to strengthen the remaining elements." },
  { name: 'Abode, Figure of', category: 'Imagery & Description', definition: "A figure describing one's homeland or dwelling place in elevated terms." },
  { name: 'Abominatio', category: 'Emotion & Tone', definition: "Expressing extreme hatred or disgust for something." },
  { name: 'Acoloutha', category: 'Classical Rhetoric', definition: "Consistency of grammatical construction throughout a passage." },
  { name: 'Accismus', category: 'Emphasis & Amplification', definition: "Feigned refusal of something one actually desires — false modesty as rhetorical strategy." },
  { name: 'Accumulatio', category: 'Repetition', definition: "Heaping up of words, arguments, or examples for cumulative effect." },
  { name: 'Acervatio', category: 'Repetition', definition: "Same as accumulatio — piling up of words or ideas for emphasis." },
  { name: 'Acrostic', category: 'Classical Rhetoric', definition: "A composition in which the first letters of successive lines spell out a word or message." },
  { name: 'Acyrologia', category: 'Wordplay', definition: "Using a word incorrectly but close in sound or meaning to the right one — a near-miss word choice." },
  { name: 'Acyron', category: 'Wordplay', definition: "Improper use of a word — using a term outside its established meaning." },
  { name: 'Adage / Adagium', category: 'Classical Rhetoric', definition: "A widely known saying accepted as true — a proverb deployed as rhetorical support." },
  { name: 'Addubitatio', category: 'Classical Rhetoric', definition: "Expressing doubt about where to begin or what to say — a performative hesitation that creates intimacy." },
  { name: 'Adjournment', category: 'Classical Rhetoric', definition: "Postponing a conclusion or decision — deferring resolution for rhetorical effect." },
  { name: 'Adjudicatio', category: 'Classical Rhetoric', definition: "The point at which judgment is delivered in a legal or argumentative context." },
  { name: 'Adjunct / Adjunctio', category: 'Classical Rhetoric', definition: "Joining of coordinate clauses without connective words — related to asyndeton." },
  { name: 'Admonitio', category: 'Emotion & Tone', definition: "A warning or gentle rebuke directed at the audience or a specific person." },
  { name: 'Adnexio', category: 'Classical Rhetoric', definition: "Attaching a conclusion to a series of premises." },
  { name: 'Adnominatio', category: 'Wordplay', definition: "Wordplay involving similar-sounding names or words — a form of paronomasia applied to proper nouns." },
  { name: 'Adynata / Adynaton', category: 'Emphasis & Amplification', definition: "A declaration of impossibility — stating something cannot be done, sometimes as hyperbolic emphasis." },
  { name: 'Aeschrologia', category: 'Classical Rhetoric', definition: "The deliberate use of low or obscene language for rhetorical effect." },
  { name: 'Aetiologia', category: 'Argument & Logic', definition: "Giving reasons or causes — explaining why something is the case." },
  { name: 'Affirmatio', category: 'Classical Rhetoric', definition: "Strong affirmation — asserting something with maximum confidence and no qualification." },
  { name: 'Aganactesis', category: 'Emotion & Tone', definition: "An expression of intense indignation — outrage made explicit and sustained." },
  { name: 'Agnominatio', category: 'Wordplay', definition: "Wordplay on similar-sounding names or words — related to paronomasia and adnominatio." },
  { name: 'Aischrologia', category: 'Classical Rhetoric', definition: "Low or offensive language used for rhetorical effect — same as aeschrologia." },
  { name: 'Alleotheta', category: 'Structure', definition: "Substitution of one grammatical form for another — using a plural where a singular is expected." },
  { name: 'Amara Irrisio', category: 'Contrast & Irony', definition: "Bitter mockery — irony deployed with cruelty rather than wit." },
  { name: 'Ambiguitas', category: 'Wordplay', definition: "Deliberate grammatical or syntactic ambiguity — a structure permitting more than one parsing." },
  { name: 'Ampliatio', category: 'Emphasis & Amplification', definition: "Enlarging a point — extending or exaggerating a statement beyond its immediate meaning." },
  { name: 'Anacephalaeosis', category: 'Emphasis & Amplification', definition: "Summary recapitulation — briefly reviewing the main points already made." },
  { name: 'Anacoloutha', category: 'Structure', definition: "Inconsistency of grammatical construction — beginning a sentence with one structure and completing it with another." },
  { name: 'Anamnesis', category: 'Classical Rhetoric', definition: "Recalling past events or statements — bringing historical material into the present argument." },
  { name: 'Anangeon', category: 'Classical Rhetoric', definition: "An expression of necessity — stating that something must be done or must be the case." },
  { name: 'Anapodoton', category: 'Structure', definition: "A sentence with a clear if-clause but no completing then-clause — the expected resolution is withheld." },
  { name: 'Anemographia', category: 'Imagery & Description', definition: "A description of the wind — a classical ekphrastic exercise." },
  { name: 'Antanagoge', category: 'Classical Rhetoric', definition: "Balancing a criticism with a compensating positive — acknowledging a fault while providing a redeeming quality." },
  { name: 'Anthropopatheia', category: 'Emotion & Tone', definition: "Attributing human emotions to God or divine beings." },
  { name: 'Anticategoria', category: 'Argument & Logic', definition: "Counter-accusation — responding to an attack by accusing the attacker of the same or worse fault." },
  { name: 'Anticipation / Procatalepsis', category: 'Argument & Logic', definition: "Anticipating and answering objections before they are raised." },
  { name: 'Antilogy', category: 'Argument & Logic', definition: "A contradiction within a speaker's own argument." },
  { name: 'Antimetabole', category: 'Repetition', definition: "Repeating words in reversed order — similar to chiasmus but applied to the same words rather than parallel structures." },
  { name: 'Antimetathesis', category: 'Sound', definition: "Reversing the terms of a proposition to disprove it." },
  { name: 'Antipersonification', category: 'Emotion & Tone', definition: "Treating a person as an object or abstraction." },
  { name: 'Antiphrasis', category: 'Contrast & Irony', definition: "Using a word in a sense opposite to its normal meaning — irony at the level of a single word." },
  { name: 'Antiprosopopoeia', category: 'Classical Rhetoric', definition: "The reverse of personification — treating what is human as if it were non-human or inanimate." },
  { name: 'Antiptosis', category: 'Structure', definition: "Substituting one grammatical case for another." },
  { name: 'Antirrhesis', category: 'Argument & Logic', definition: "Rejecting an argument, accusation, or authority as irrelevant or insufficient." },
  { name: 'Antisagoge', category: 'Argument & Logic', definition: "Offering a reward to compensate for an imposed burden — concession with compensation." },
  { name: 'Antistasis', category: 'Contrast & Irony', definition: "Repeating a word in a different or contrary sense." },
  { name: 'Antitheton', category: 'Contrast & Irony', definition: "The formal statement of a contrast — the rhetorical argument from opposition." },
  { name: 'Antonomasia', category: 'Wordplay', definition: "Substituting a descriptive phrase or epithet for a proper name, or a proper name for a common noun." },
  { name: 'Apagoresis', category: 'Emotion & Tone', definition: "Forbidding an action — a rhetorical prohibition." },
  { name: 'Aphorismus', category: 'Classical Rhetoric', definition: "A short statement calling into question the use of a particular word or expression." },
  { name: 'Apocarteresis', category: 'Emotion & Tone', definition: "Expressing despair and giving up hope for improvement." },
  { name: 'Apodixis', category: 'Argument & Logic', definition: "Proving a point from common experience or universal knowledge." },
  { name: 'Apodioxis', category: 'Classical Rhetoric', definition: "Rejecting something as unworthy of consideration." },
  { name: 'Apologue', category: 'Classical Rhetoric', definition: "A short fable or moral tale — narrative as argument." },
  { name: 'Apophasis', category: 'Classical Rhetoric', definition: "Seeming to deny something while actually asserting it — I will not mention the fact that..." },
  { name: 'Apoplanesis', category: 'Classical Rhetoric', definition: "Digressing from the main point to avoid something difficult or painful." },
  { name: 'Aporia', category: 'Classical Rhetoric', definition: "Genuine or performed doubt or hesitation — expressing uncertainty as a rhetorical device." },
  { name: 'Aposiopesis', category: 'Brevity & Omission', definition: "Breaking off speech mid-sentence — leaving a thought incomplete for dramatic effect." },
  { name: 'Apothegm', category: 'Classical Rhetoric', definition: "A pithy, memorable statement of a general truth — a pointed form of the maxim." },
  { name: 'Apparent Refusal', category: 'Classical Rhetoric', definition: "Seeming to decline something while actually asserting it — a form of apophasis." },
  { name: 'Appositio', category: 'Classical Rhetoric', definition: "Placing one phrase beside another to rename or clarify — same as apposition." },
  { name: 'Ara', category: 'Emotion & Tone', definition: "A curse or imprecation — wishing harm upon an opponent." },
  { name: 'Articulus', category: 'Structure', definition: "A figure of separation — using short successive clauses — related to asyndeton." },
  { name: 'Aschematismus', category: 'Wordplay', definition: "Plain speech without rhetorical figures — deliberate absence of ornamentation." },
  { name: 'Aschematiston', category: 'Classical Rhetoric', definition: "Same as aschematismus — unadomed direct expression." },
  { name: 'Asphalia', category: 'Classical Rhetoric', definition: "Offering guarantees or assurances — promising certainty as a rhetorical move." },
  { name: 'Assumptio', category: 'Argument & Logic', definition: "Taking up a point from the opponent's argument and using it against them." },
  { name: 'Avancer', category: 'Classical Rhetoric', definition: "A figure that advances or promotes an argument — moving the case forward." },
  { name: 'Aversio', category: 'Emotion & Tone', definition: "Turning away — a form of apostrophe where the speaker turns from the audience to address something else." },
  { name: 'Barbarism', category: 'Classical Rhetoric', definition: "Using foreign or non-standard words incorrectly — though in hip hop dialect use is deliberate, not barbaristic." },
  { name: 'Battologia', category: 'Repetition', definition: "Needless repetition of the same idea in different words without adding meaning." },
  { name: 'Bdelygmia', category: 'Emotion & Tone', definition: "Expressing hatred or disgust — a sustained expression of revulsion." },
  { name: 'Benedictio', category: 'Classical Rhetoric', definition: "A blessing or prayer — formal words of benediction." },
  { name: 'Bomphiologia', category: 'Classical Rhetoric', definition: "Inflated or boastful speech — grandiose self-praise without earned basis." },
  { name: 'Brachiepia', category: 'Brevity & Omission', definition: "Extreme brevity in expression." },
  { name: 'Brachylogia', category: 'Brevity & Omission', definition: "Condensed expression — saying much in very few words." },
  { name: 'Cacemphaton', category: 'Wordplay', definition: "A phrase with an unintentional or deliberate obscene double meaning." },
  { name: 'Cacophonia', category: 'Sound', definition: "Harsh or unpleasant sound — related to cacophony in the main document." },
  { name: 'Cacosyntheton', category: 'Sound', definition: "An awkward or unpleasant arrangement of words." },
  { name: 'Cacozelia', category: 'Classical Rhetoric', definition: "Affectation in style — straining for effect to the point of failure." },
  { name: 'Casus Pro Casu', category: 'Structure', definition: "Substituting one grammatical case for another." },
  { name: 'Catachresis', category: 'Wordplay', definition: "Misuse or extreme extension of a word beyond its normal meaning — creative or forced metaphor." },
  { name: 'Catacosmesis', category: 'Classical Rhetoric', definition: "Arrangement of words in order of increasing importance — see climax in main document." },
  { name: 'Cataphasis', category: 'Classical Rhetoric', definition: "Positive assertion — affirming something directly." },
  { name: 'Cataplexis', category: 'Emotion & Tone', definition: "A threat — promising punishment for specific behavior." },
  { name: 'Categoria', category: 'Classical Rhetoric', definition: "Direct accusation naming the crime." },
  { name: 'Cause Shown', category: 'Classical Rhetoric', definition: "An argument that establishes the cause or reason behind a position." },
  { name: 'Change of Name', category: 'Classical Rhetoric', definition: "Substituting one name for another — related to antonomasia." },
  { name: 'Characterismus', category: 'Emotion & Tone', definition: "Description of a person's mental and spiritual qualities — character portrait." },
  { name: 'Charientismus', category: 'Classical Rhetoric', definition: "Softening an unpleasant remark through graceful expression — saying difficult things pleasantly." },
  { name: 'Chorographia', category: 'Imagery & Description', definition: "Description of a country or region." },
  { name: 'Chreia', category: 'Classical Rhetoric', definition: "A short account of a saying or action attributed to a specific person — the anecdote as rhetorical proof." },
  { name: 'Chronographia', category: 'Imagery & Description', definition: "Description of a time or period — ekphrasis applied to temporal rather than spatial subjects." },
  { name: 'Circumlocutio', category: 'Brevity & Omission', definition: "Expressing something in many words that could be expressed in few — periphrasis." },
  { name: 'Coenotes', category: 'Structure', definition: "A figure combining two or more sentences under a single subject or predicate." },
  { name: 'Colon', category: 'Classical Rhetoric', definition: "A clause — a rhythmic unit of expression in classical rhetoric." },
  { name: 'Combined Repetition', category: 'Repetition', definition: "The use of multiple repetition devices simultaneously." },
  { name: 'Comma', category: 'Classical Rhetoric', definition: "A very short rhythmic clause in classical rhetoric — the shortest unit of expression." },
  { name: 'Common Cause', category: 'Classical Rhetoric', definition: "An argument based on shared interest between speaker and audience." },
  { name: 'Compensatio', category: 'Argument & Logic', definition: "Balancing one consideration against another — the rhetorical weighing of pros and cons." },
  { name: 'Complexio', category: 'Structure', definition: "Combining anaphora with epistrophe — identical with symploce." },
  { name: 'Compositum ex Contrariis', category: 'Classical Rhetoric', definition: "Joining contraries in one statement — related to oxymoron and paradox." },
  { name: 'Comprobatio', category: 'Classical Rhetoric', definition: "Praising one's judges or audience to gain goodwill." },
  { name: 'Conciliatio', category: 'Classical Rhetoric', definition: "Winning over a hostile or indifferent audience through strategic concession." },
  { name: 'Condescensio', category: 'Classical Rhetoric', definition: "Adjusting one's language to the level of the audience — not pejorative, a communicative strategy." },
  { name: 'Congeries', category: 'Repetition', definition: "A heap or accumulation of words, phrases, or ideas for cumulative effect." },
  { name: 'Conjunctio', category: 'Structure', definition: "Joining of elements — related to zeugma and conjunction." },
  { name: 'Contencion / Contentio', category: 'Classical Rhetoric', definition: "Striving or straining — an expression of struggle or effort." },
  { name: 'Continued Metaphor', category: 'Comparison', definition: "A metaphor sustained across multiple clauses — see extended metaphor in main document." },
  { name: 'Contractio', category: 'Sound', definition: "Contraction of syllables — a grammatical compression." },
  { name: 'Contrarium', category: 'Argument & Logic', definition: "An argument from the opposite — using the contrary to prove a point." },
  { name: 'Conversio', category: 'Repetition', definition: "Turning back — returning to an earlier point or repeating words at line endings." },
  { name: 'Correctio', category: 'Classical Rhetoric', definition: "Self-correction — taking back what was said and replacing it with a more accurate statement." },
  { name: 'Counterchange', category: 'Classical Rhetoric', definition: "A reversal or exchange of terms — related to chiasmus and antimetabole." },
  { name: 'Deesis', category: 'Classical Rhetoric', definition: "An earnest entreaty or supplication." },
  { name: 'Dehortatio', category: 'Emotion & Tone', definition: "A dissuasion — warning against a course of action." },
  { name: 'Dendrographia', category: 'Imagery & Description', definition: "Description of a tree or trees." },
  { name: 'Deprecatio', category: 'Classical Rhetoric', definition: "Seeking pardon or forgiveness — pleading to be excused." },
  { name: 'Descriptio', category: 'Imagery & Description', definition: "A detailed description of a person, place, or thing — general ekphrasis." },
  { name: 'Diaeresis', category: 'Classical Rhetoric', definition: "Separating a compound idea into its constituent parts." },
  { name: 'Dialysis', category: 'Argument & Logic', definition: "Presenting alternatives exhaustively and then eliminating all but one." },
  { name: 'Dialyton', category: 'Classical Rhetoric', definition: "A figure of disjunction — separating elements that might otherwise be connected." },
  { name: 'Dianoea', category: 'Argument & Logic', definition: "Presenting two opposite sides of a case fairly and then choosing the better." },
  { name: 'Diaphora', category: 'Wordplay', definition: "Using the same word in different senses in close proximity." },
  { name: 'Diaskeue', category: 'Imagery & Description', definition: "An amplification of striking details — making the vivid more vivid." },
  { name: 'Diastole', category: 'Sound', definition: "Lengthening a syllable that is normally short — opposite of systole." },
  { name: 'Diasyrmus', category: 'Contrast & Irony', definition: "Rejecting an argument through ridicule rather than refutation." },
  { name: 'Diazeugma', category: 'Structure', definition: "Multiple predicates attached to a single subject — the subject governs many actions." },
  { name: 'Dicaeologia', category: 'Argument & Logic', definition: "Justifying an action by showing it was necessary — defense through necessity." },
  { name: 'Digressio', category: 'Classical Rhetoric', definition: "A deliberate departure from the main subject — the controlled digression." },
  { name: 'Dilemma', category: 'Argument & Logic', definition: "Presenting an opponent with two choices, both unfavorable." },
  { name: 'Dirimens Copulatio', category: 'Argument & Logic', definition: "Adding a point that equally balances or outweighs the previous point." },
  { name: 'Distributio', category: 'Classical Rhetoric', definition: "Dividing a subject into its parts and addressing each in turn." },
  { name: 'Doubtfull / Dubitatio', category: 'Classical Rhetoric', definition: "Expressing genuine or performed uncertainty about a point." },
  { name: 'Ecphonesis', category: 'Emotion & Tone', definition: "An emotional exclamation — a cry of feeling rather than a statement." },
  { name: 'Ecphrasis', category: 'Imagery & Description', definition: "Detailed description of a work of art, place, or object — making the absent vividly present." },
  { name: 'Ecthlipsis', category: 'Sound', definition: "The suppression of a final syllable — a form of apocope in classical prosody." },
  { name: 'Effictio', category: 'Imagery & Description', definition: "A portrait of a person through detailed physical description." },
  { name: 'Elenchus', category: 'Argument & Logic', definition: "Refutation — proving the opponent's position wrong through logical argument." },
  { name: 'Enallage', category: 'Structure', definition: "The substitution of one grammatical form for another — tense, number, or person." },
  { name: 'Enantiosis', category: 'Contrast & Irony', definition: "Using opposites to confirm or expand a point." },
  { name: 'Enargia', category: 'Imagery & Description', definition: "Vivid description that creates the sensation of presence — a subcategory of hypotyposis." },
  { name: 'Encomium', category: 'Classical Rhetoric', definition: "A formal speech of praise — celebrating a person, place, or thing." },
  { name: 'Energia', category: 'Classical Rhetoric', definition: "The forcefulness and vivid quality of expression — the feeling that language has kinetic energy." },
  { name: 'Enigma', category: 'Wordplay', definition: "A deliberate riddle — obscure language that must be decoded." },
  { name: 'Enthymeme', category: 'Argument & Logic', definition: "An argument with an implied rather than stated premise — a syllogism with one term left to the audience's inference." },
  { name: 'Enumeratio', category: 'Classical Rhetoric', definition: "Listing the parts of a whole or the details of a subject." },
  { name: 'Epanodos', category: 'Repetition', definition: "Repeating words in reversed order or returning to the beginning after a digression." },
  { name: 'Epanorthosis', category: 'Classical Rhetoric', definition: "Self-correction for emphasis or precision — restating more accurately what was just said." },
  { name: 'Epergesis', category: 'Emphasis & Amplification', definition: "Adding an explanation immediately after a statement." },
  { name: 'Epexegesis', category: 'Emphasis & Amplification', definition: "Explaining or expanding on what has just been said." },
  { name: 'Epicrisis', category: 'Classical Rhetoric', definition: "Quoting from an authority and then commenting on the quotation." },
  { name: 'Epimone', category: 'Repetition', definition: "Frequent repetition of a phrase or question to fix it in the listener's mind." },
  { name: 'Epiphonema', category: 'Classical Rhetoric', definition: "A memorable concluding statement — a pithy summarizing remark that closes an argument." },
  { name: 'Epiplexis', category: 'Classical Rhetoric', definition: "Asking sharp questions to rebuke or reproach — the rhetorical question as accusation." },
  { name: 'Epitasis', category: 'Emphasis & Amplification', definition: "An intensification — adding to what was just said to make it stronger." },
  { name: 'Epitheton', category: 'Classical Rhetoric', definition: "An adjective or descriptive phrase expressing a quality of the person or thing — the epithet." },
  { name: 'Episynaloephe', category: 'Sound', definition: "Contraction of two syllables by elision at a word boundary." },
  { name: 'Epitrochasmus', category: 'Classical Rhetoric', definition: "Quickly running through a list of points — rapid enumeration." },
  { name: 'Epitrope', category: 'Classical Rhetoric', definition: "Granting permission to an opponent while confident the result will favor you." },
  { name: 'Epizeugma', category: 'Structure', definition: "A figure in which one verb governs several clauses." },
  { name: 'Erotema', category: 'Classical Rhetoric', definition: "A rhetorical question — asked for effect rather than information, with the answer implied." },
  { name: 'Eucharistia', category: 'Emotion & Tone', definition: "An expression of gratitude — giving thanks as a rhetorical move." },
  { name: 'Euche', category: 'Emotion & Tone', definition: "A prayer or vow — direct address to a divine being." },
  { name: 'Eulogia', category: 'Classical Rhetoric', definition: "Speaking well of someone — formal praise." },
  { name: 'Euphemismus', category: 'Classical Rhetoric', definition: "Substituting a pleasant or mild expression for a harsh or taboo one." },
  { name: 'Eustathia', category: 'Classical Rhetoric', definition: "Firmness and steadiness in speaking — unwavering rhetorical resolve." },
  { name: 'Eutrepismus', category: 'Classical Rhetoric', definition: "Numbering and ordering the points to be made — I have three things to say, first..." },
  { name: 'Example / Paradigma', category: 'Emotion & Tone', definition: "An example drawn from history or common experience to support an argument." },
  { name: 'Excitatio', category: 'Emotion & Tone', definition: "Exciting or rousing the audience — creating enthusiasm or urgency." },
  { name: 'Exclamatio', category: 'Emotion & Tone', definition: "An exclamation — strong emotional expression." },
  { name: 'Excursus', category: 'Classical Rhetoric', definition: "A digression — extended departure from the main point." },
  { name: 'Exergasia', category: 'Repetition', definition: "Repeating the same idea through different figures — varied expression of a single point." },
  { name: 'Exouthenismos', category: 'Classical Rhetoric', definition: "Contemptuous dismissal — treating something as beneath consideration." },
  { name: 'Expeditio', category: 'Argument & Logic', definition: "Eliminating all alternatives except the one to be argued for." },
  { name: 'Expolitio', category: 'Repetition', definition: "Repeating the same thought in different words and with different examples." },
  { name: 'Exuscitatio', category: 'Emotion & Tone', definition: "Exciting the emotions of the audience — deliberate pathos." },
  { name: 'Frequentatio', category: 'Repetition', definition: "Heaping up the strongest points from what has been said — summarizing through accumulation." },
  { name: 'Geographia', category: 'Imagery & Description', definition: "Description of places generally — geographical ekphrasis." },
  { name: 'Gnome', category: 'Classical Rhetoric', definition: "A short moral statement of general truth — a maxim or sententia." },
  { name: 'Graecismus', category: 'Classical Rhetoric', definition: "Use of a Greek idiom or construction — primarily relevant in Latin rhetorical context." },
  { name: 'Hendiadys', category: 'Structure', definition: "Expressing a single idea through two coordinate nouns rather than a noun and modifier." },
  { name: 'Heterogenium', category: 'Classical Rhetoric', definition: "Answering a question with an irrelevant response to avoid it." },
  { name: 'Homiologia', category: 'Classical Rhetoric', definition: "Sameness of style or content — monotony, sometimes deliberate." },
  { name: 'Homoeoprophoron', category: 'Sound', definition: "Alliteration across an entire clause — every word beginning with the same sound." },
  { name: 'Homoeosis', category: 'Comparison', definition: "Comparison through resemblance — a broad category including metaphor, simile, and related devices." },
  { name: 'Homoioptoton', category: 'Sound', definition: "Ending successive words with the same grammatical case ending." },
  { name: 'Homoioteleuton', category: 'Sound', definition: "Ending successive clauses with the same or similar sounds — similar to rhyme at the end of phrases." },
  { name: 'Horismus', category: 'Classical Rhetoric', definition: "A brief definition — stating exactly what a term means." },
  { name: 'Hydrographia', category: 'Imagery & Description', definition: "Description of bodies of water." },
  { name: 'Hypallage', category: 'Classical Rhetoric', definition: "Transposing the natural relationship between elements of a sentence — the transferred epithet." },
  { name: 'Hyperbaton', category: 'Structure', definition: "Any inversion or transposition of the natural word order." },
  { name: 'Hypophora', category: 'Argument & Logic', definition: "Raising a question and then answering it — self-interrogation that controls the argument." },
  { name: 'Hypotyposis', category: 'Imagery & Description', definition: "Vivid description that makes absent things present — the imagination made to see." },
  { name: 'Hypozeugma', category: 'Structure', definition: "A zeugma in which the governing word appears at the end of the construction." },
  { name: 'Hypozeuxis', category: 'Classical Rhetoric', definition: "Every clause having its own subject and predicate — complete independence of each element." },
  { name: 'Hysterologia', category: 'Structure', definition: "Placing later in the sentence what logically should come first." },
  { name: 'Hysteron Proteron', category: 'Structure', definition: "Putting what should come last first — reversal of normal logical or temporal sequence." },
  { name: 'Icon', category: 'Comparison', definition: "A comparison that describes by resemblance — a visual simile." },
  { name: 'Indignatio', category: 'Emotion & Tone', definition: "A forceful expression of indignation — controlled outrage as rhetorical climax." },
  { name: 'Inopinaturm', category: 'Classical Rhetoric', definition: "The unexpected — introducing something the audience did not anticipate." },
  { name: 'Insinuatio', category: 'Classical Rhetoric', definition: "Winning over a hostile audience indirectly — establishing goodwill before the main argument." },
  { name: 'Interrogatio', category: 'Classical Rhetoric', definition: "A direct question — distinct from the rhetorical question in that an answer may be expected." },
  { name: 'Inter Se Pugnantia', category: 'Argument & Logic', definition: "Arguments that contradict each other — pointing out internal inconsistency in an opponent's case." },
  { name: 'Intimation', category: 'Classical Rhetoric', definition: "Suggesting something without stating it directly — a hint or implication." },
  { name: 'Litotes', category: 'Contrast & Irony', definition: "Understatement through negation of the opposite — see main Figurative Language entry." },
  { name: 'Macrologia', category: 'Brevity & Omission', definition: "The use of more words than necessary — a verbose style." },
  { name: 'Martyria', category: 'Classical Rhetoric', definition: "Confirming something by personal observation or experience." },
  { name: 'Maxim', category: 'Classical Rhetoric', definition: "A short general truth — a concise statement of principle." },
  { name: 'Medela', category: 'Classical Rhetoric', definition: "A correction that heals or mitigates what was previously said." },
  { name: 'Meiosis', category: 'Contrast & Irony', definition: "Deliberate understatement — making something seem smaller than it is." },
  { name: 'Membrum', category: 'Classical Rhetoric', definition: "A short rhythmic clause in classical rhetoric." },
  { name: 'Mempsis', category: 'Emotion & Tone', definition: "Complaining about one's situation and asking for help." },
  { name: 'Merismus', category: 'Classical Rhetoric', definition: "Dividing a whole into its parts — comprehensive enumeration." },
  { name: 'Mesarchia', category: 'Repetition', definition: "Repetition of the same word at the beginning and middle of successive sentences." },
  { name: 'Mesodiplosis', category: 'Repetition', definition: "Repetition of the same word in the middle of successive clauses." },
  { name: 'Mesozeugma', category: 'Structure', definition: "A zeugma in which the governing word appears in the middle of the construction." },
  { name: 'Metabasis', category: 'Classical Rhetoric', definition: "A transition — briefly summarizing what has been said and introducing what will follow." },
  { name: 'Metalepsis', category: 'Wordplay', definition: "Using a word in a figurative sense connecting to its original sense through a chain of associations." },
  { name: 'Metallage', category: 'Wordplay', definition: "Using a word as if it were a different part of speech — functional shift." },
  { name: 'Metastasis', category: 'Classical Rhetoric', definition: "Quickly passing over something while pretending to acknowledge it." },
  { name: 'Metathesis', category: 'Sound', definition: "Transposing letters or sounds within a word." },
  { name: 'Mycterismus', category: 'Contrast & Irony', definition: "A sarcastic remark accompanied by gesture — mockery that includes performance." },
  { name: 'Noema', category: 'Wordplay', definition: "A statement requiring thought to understand — deliberately obscured meaning. See main Wordplay entry." },
  { name: 'Oeonismus', category: 'Classical Rhetoric', definition: "An omen or augury — interpreting natural signs as meaningful." },
  { name: 'Ominatio', category: 'Emotion & Tone', definition: "A prediction of evil or catastrophe." },
  { name: 'Onedismus', category: 'Classical Rhetoric', definition: "Reproaching someone for ingratitude or impiety." },
  { name: 'Optatio', category: 'Emotion & Tone', definition: "An exclamation of desire — wishing for something as rhetorical emphasis." },
  { name: 'Orcos', category: 'Classical Rhetoric', definition: "A solemn oath or swearing." },
  { name: 'Paenismus', category: 'Classical Rhetoric', definition: "Praise of God — a hymn of thanks." },
  { name: 'Parabola', category: 'Comparison', definition: "An extended simile or comparison — a narrative comparison." },
  { name: 'Paradiastole', category: 'Sound', definition: "Substituting a favorable description for an unfavorable one — calling rashness courage." },
  { name: 'Paradiegesis', category: 'Emotion & Tone', definition: "A digressive narrative inserted into the main argument." },
  { name: 'Paraenesis', category: 'Emotion & Tone', definition: "Hortatory advice — counsel about future conduct." },
  { name: 'Paragoge', category: 'Sound', definition: "Addition of a sound or syllable to the end of a word." },
  { name: 'Paralipsis', category: 'Emotion & Tone', definition: "Seeming to pass over something while actually drawing attention to it — I will not mention..." },
  { name: 'Paramythia', category: 'Emotion & Tone', definition: "Consolation — words of comfort." },
  { name: 'Parathesis', category: 'Emotion & Tone', definition: "Placing two things side by side for comparison without explicit comment." },
  { name: 'Parecbasis', category: 'Classical Rhetoric', definition: "A digression." },
  { name: 'Paregmenon', category: 'Wordplay', definition: "Using words derived from the same root near each other." },
  { name: 'Parelcon', category: 'Classical Rhetoric', definition: "Adding a redundant word that does not change the meaning." },
  { name: 'Parembole', category: 'Classical Rhetoric', definition: "Inserting an additional argument into the middle of another argument." },
  { name: 'Pareuresis', category: 'Classical Rhetoric', definition: "Offering excuses or justifications." },
  { name: 'Paroemia', category: 'Classical Rhetoric', definition: "A proverb used as rhetorical evidence." },
  { name: 'Paroemion', category: 'Sound', definition: "Alliteration at its most extreme — every word beginning with the same letter." },
  { name: 'Paromoiosis', category: 'Sound', definition: "Grammatical parallelism with sound similarity — both structure and sound echo each other." },
  { name: 'Paromologia', category: 'Argument & Logic', definition: "Conceding a point to make a stronger one — giving up a small argument to win a large one." },
  { name: 'Parrhesia', category: 'Classical Rhetoric', definition: "Speaking one's mind freely, even at risk — frank and potentially dangerous speech." },
  { name: 'Pathopoeia', category: 'Emotion & Tone', definition: "Exciting emotion through vivid description — creating feeling rather than describing it." },
  { name: 'Perclusio', category: 'Emotion & Tone', definition: "A threat — cutting off the opponent's possibilities by warning of consequences." },
  { name: 'Periergia', category: 'Classical Rhetoric', definition: "Excessive care or embellishment — overdone ornamentation." },
  { name: 'Period', category: 'Structure', definition: "A complete grammatical sentence — a full unit of expression." },
  { name: 'Periphrasis', category: 'Brevity & Omission', definition: "Expressing something in more words than necessary — circumlocution for effect or decorum." },
  { name: 'Perissologia', category: 'Brevity & Omission', definition: "Using more words than the sense requires." },
  { name: 'Peristasis', category: 'Emphasis & Amplification', definition: "Amplification of circumstances — building context to strengthen an argument." },
  { name: 'Permutatio', category: 'Classical Rhetoric', definition: "Exchange of terms — using one in place of another." },
  { name: 'Philophronesis', category: 'Classical Rhetoric', definition: "Softening an audience's displeasure through gentle, friendly speech." },
  { name: 'Pleonasm', category: 'Brevity & Omission', definition: "Using more words than necessary — sometimes for emphasis, sometimes as a fault." },
  { name: 'Polyptoton', category: 'Wordplay', definition: "Using the same word in different grammatical forms in close proximity." },
  { name: 'Pragmatographia', category: 'Imagery & Description', definition: "Vivid description of an action or event." },
  { name: 'Procatalepsis', category: 'Argument & Logic', definition: "Anticipating objections and answering them before they are raised." },
  { name: 'Proclees', category: 'Emotion & Tone', definition: "Inciting to action — urging forward through challenge or taunt." },
  { name: 'Prodiorthosis', category: 'Classical Rhetoric', definition: "Preparing the audience for something shocking or unexpected." },
  { name: 'Proecthesis', category: 'Classical Rhetoric', definition: "Offering a justification before making a request." },
  { name: 'Prolepsis', category: 'Argument & Logic', definition: "Taking up an anticipated objection and answering it." },
  { name: 'Prosapodosis', category: 'Argument & Logic', definition: "Providing reasons for each of several preceding statements." },
  { name: 'Proslepsis', category: 'Classical Rhetoric', definition: "Adding a conclusion that completes the sense of what preceded." },
  { name: 'Prosonomasia', category: 'Wordplay', definition: "A name that reflects or puns on the person's character or deeds." },
  { name: 'Prosopographia', category: 'Imagery & Description', definition: "A description of an absent or imaginary person's appearance." },
  { name: 'Prosphonesis', category: 'Classical Rhetoric', definition: "Addressing the audience directly with respect or courtesy." },
  { name: 'Protherapeia', category: 'Classical Rhetoric', definition: "Preparing the audience to be receptive before making the main point." },
  { name: 'Prothesis', category: 'Sound', definition: "Adding a syllable to the beginning of a word." },
  { name: 'Protrope', category: 'Classical Rhetoric', definition: "Urging action — a call to do something immediately." },
  { name: 'Prozeugma', category: 'Structure', definition: "A zeugma in which the governing word precedes all the clauses it governs." },
  { name: 'Pysma', category: 'Argument & Logic', definition: "Asking multiple questions at once without waiting for answers — a rhetorical barrage." },
  { name: 'Ratiocinatio', category: 'Argument & Logic', definition: "Drawing a conclusion through a chain of reasoning — the syllogism made rhetorical." },
  { name: 'Repetitio', category: 'Repetition', definition: "General repetition of a word or phrase for emphasis." },
  { name: 'Repotia', category: 'Argument & Logic', definition: "Reviving an argument after it has been attacked." },
  { name: 'Restrictio', category: 'Argument & Logic', definition: "Qualifying a general statement by excluding specific cases." },
  { name: 'Rhetorical Question', category: 'Classical Rhetoric', definition: "A question asked for effect rather than information — the answer is assumed or implied." },
  { name: 'Sarcasmus', category: 'Contrast & Irony', definition: "Bitter irony — mockery with genuine hostile intent." },
  { name: 'Scesis Onomaton', category: 'Structure', definition: "A sentence constructed entirely of nouns and adjectives, without verbs." },
  { name: 'Schematismus', category: 'Wordplay', definition: "Veiled or allusive speech — saying one thing while meaning another." },
  { name: 'Scheme', category: 'Classical Rhetoric', definition: "A generic term for any figure of arrangement — a meta-category, not a device itself." },
  { name: 'Scurra', category: 'Classical Rhetoric', definition: "Buffoonery — using humor and mockery for rhetorical effect." },
  { name: 'Skotison', category: 'Wordplay', definition: "Deliberately obscure language — making things unclear on purpose." },
  { name: 'Sententia', category: 'Classical Rhetoric', definition: "A pithy and memorable statement of general truth — the aphorism deployed as conclusion." },
  { name: 'Sermocinatio', category: 'Classical Rhetoric', definition: "Speaking in the voice of another person. See main Dramatic Dialogue entry." },
  { name: 'Simile', category: 'Comparison', definition: "An explicit comparison using like or as. See main Figurative Language entry." },
  { name: 'Solecismus', category: 'Wordplay', definition: "A grammatical error used deliberately for rhetorical effect." },
  { name: 'Soraismus', category: 'Classical Rhetoric', definition: "Mixing languages in an affected or pretentious way." },
  { name: 'Sorites', category: 'Argument & Logic', definition: "A chain of syllogisms — each conclusion becomes a premise for the next." },
  { name: 'Subjectio', category: 'Argument & Logic', definition: "Asking questions of oneself and answering them — a form of self-interrogation." },
  { name: 'Sustentatio', category: 'Classical Rhetoric', definition: "Keeping the audience in suspense by delaying the resolution of a question." },
  { name: 'Syllepsis', category: 'Structure', definition: "Using one word to govern two or more others, each in a different sense." },
  { name: 'Syllogismus', category: 'Argument & Logic', definition: "A formal logical argument with two premises and a conclusion." },
  { name: 'Symperasma', category: 'Classical Rhetoric', definition: "A concluding statement that summarizes what has been proven." },
  { name: 'Synaeresis', category: 'Sound', definition: "Contraction of two syllables into one." },
  { name: 'Synaloepha', category: 'Sound', definition: "Elision of a vowel at the end of one word before a vowel beginning the next." },
  { name: 'Synathroesmus', category: 'Repetition', definition: "Heaping up of words for amplification — related to accumulatio and congeries." },
  { name: 'Syncatabasis', category: 'Classical Rhetoric', definition: "Condescending to speak on the level of the audience — adjusting register downward." },
  { name: 'Syncategorema', category: 'Classical Rhetoric', definition: "A word that has meaning only in combination with other words — function words in linguistic terms." },
  { name: 'Synchoresis', category: 'Classical Rhetoric', definition: "Granting permission to an opponent while confident the result will favor you." },
  { name: 'Synchysis', category: 'Structure', definition: "A confused arrangement of words — deliberate disorder for effect." },
  { name: 'Syncrisis', category: 'Comparison', definition: "A comparison of opposites in parallel clauses." },
  { name: 'Synoeciosis', category: 'Contrast & Irony', definition: "Joining contraries in one statement — related to oxymoron." },
  { name: 'Synonymia', category: 'Repetition', definition: "Using several synonyms in succession for amplification." },
  { name: 'Synthesis', category: 'Classical Rhetoric', definition: "A combination of all available arguments — comprehensive conclusion." },
  { name: 'Syntheton', category: 'Structure', definition: "Coupling together two or more words." },
  { name: 'Synzeugma', category: 'Structure', definition: "A single word governing a construction both before and after it." },
  { name: 'Systrophe', category: 'Classical Rhetoric', definition: "Heaping up of definitions or descriptions without logical order." },
  { name: 'Tapinosis', category: 'Contrast & Irony', definition: "Debasing language — using low or diminishing words to undercut what is described." },
  { name: 'Tasis', category: 'Sound', definition: "Sustaining a sound or argument — prolonged expression." },
  { name: 'Tautologia', category: 'Repetition', definition: "Needless repetition of the same idea in different words." },
  { name: 'Taxis', category: 'Structure', definition: "Orderly arrangement — placing elements in their proper order." },
  { name: 'Thaumasmus', category: 'Emotion & Tone', definition: "An expression of wonder — exclamation at something remarkable." },
  { name: 'Topothesia', category: 'Imagery & Description', definition: "Description of an imaginary place." },
  { name: 'Topographia', category: 'Imagery & Description', definition: "Description of a specific place — see imagery section for the hip hop application." },
  { name: 'Traductio', category: 'Wordplay', definition: "Using the same word several times in different senses or with different emphases." },
  { name: 'Transitio', category: 'Classical Rhetoric', definition: "A brief statement connecting two parts of an argument." },
  { name: 'Transplacement', category: 'Repetition', definition: "Using the same word repeatedly but in different positions in each clause." },
  { name: 'Tricolon', category: 'Structure', definition: "A series of three parallel elements — words, phrases, or clauses." },
  { name: 'Verborum Bombus', category: 'Sound', definition: "Bombastic or high-sounding language without substance." },
  { name: 'Zeugma', category: 'Structure', definition: "One word governing two or more others, applying in different senses to each." },
];

export { DEVICES };
